version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=your@email.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - industrace-network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: industrace_user
      POSTGRES_PASSWORD: secure_password_123
      POSTGRES_DB: industrace
    volumes:
      - industrace_postgres_data:/var/lib/postgresql/data
    networks:
      - industrace-network
    labels:
      - "traefik.enable=false"
    expose:
      - "5432"

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://industrace_user:secure_password_123@db:5432/industrace
      - SECRET_KEY=your-secret-key
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - CORS_ORIGINS=http://localhost,https://localhost,http://industrace.localhost
    depends_on:
      - db
    networks:
      - industrace-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`industrace.localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.routers.backend.priority=100"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"

  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://industrace.localhost/api
    depends_on:
      - backend
    networks:
      - industrace-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`industrace.localhost`) && !PathPrefix(`/api`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.priority=10"
      - "traefik.http.services.frontend.loadbalancer.server.port=5173"

volumes:
  industrace_postgres_data:

networks:
  industrace-network:
    driver: bridge