# Traefik certificates configuration
# This file defines the custom certificates for internal domains

tls:
  certificates:
    - certFile: /etc/traefik/certs/cert.crt
      keyFile: /etc/traefik/certs/key.key
      stores:
        - default
      domains:
        - main: "industrace.local"
          sans:
            - "www.industrace.local"
            - "traefik.industrace.local"

  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/cert.crt
        keyFile: /etc/traefik/certs/key.key
